apiVersion: apps/v1
kind: Deployment
metadata:
  name: azdo-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      name: agent
  template:
    metadata:
      labels:
        name: agent
    spec:
      containers:
        - name: azdo-agent
          image: "azdoagent.azurecr.io/azdevopsagent:2.0"
          env:
          - name: AZP_URL
            value: "https://dev.azure.com/nikolaivetic-containers"
          - name: AZP_TOKEN
            value: "5g5epkiwgida25lst6bdgchpnuuysi4btr44kcbaq6v4jlcpo23q"
          - name: AZP_POOL
            value: "aks-agent-pool"
          - name: AZP_AGENT_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
#          envFrom:
#            - secretRef:
#                name: azdosecret
