apiVersion: apps/v1
kind: Deployment
metadata:
  name: azdo-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      name: agent
  template:
    metadata:
      labels:
        name: agent
    spec:
      containers:
        - name: azdo-agent
          image: "<YOUR REGISTRY>.azurecr.io/devops-agent:1.0"
          env:
          - name: AZP_URL
            value: "https://dev.azure.com/<YOUR PROJECT>"
          - name: AZP_TOKEN
            value: "<YOUR DevOps PAT>"
          - name: AZP_POOL
            value: "aks-agent-pool"
          - name: AZP_AGENT_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
